"""Browser-based first-run setup wizard.

Run with:  argus-setup-gui
Opens http://localhost:8888 and walks through credentials → accounts →
watchlist → risk settings, then writes .env and stores secrets in the
OS keychain.  Shuts down automatically when setup completes.
"""

from __future__ import annotations

import os
import pathlib
import subprocess
import sys
import threading
import webbrowser
from typing import Any

import uvicorn
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, JSONResponse

_ROOT = pathlib.Path(__file__).parent.parent  # project root
_ENV_FILE = _ROOT / ".env"

app = FastAPI(docs_url=None, redoc_url=None)

_shutdown_event = threading.Event()


# ── helpers ────────────────────────────────────────────────────────────────────

def _store_secret(key: str, value: str) -> None:
    try:
        from argus.secrets import set_secret
        set_secret(key, value)
    except Exception:
        pass


def _write_env(fields: dict[str, str]) -> None:
    lines = [
        "# Argus configuration — generated by setup wizard\n",
        "# Secrets (API keys, passwords) are stored in the OS keychain.\n\n",
    ]
    for k, v in fields.items():
        lines.append(f"{k}={v}\n")
    _ENV_FILE.write_text("".join(lines))
    _ENV_FILE.chmod(0o600)


# ── routes ─────────────────────────────────────────────────────────────────────

@app.get("/", response_class=HTMLResponse)
async def wizard_page() -> HTMLResponse:
    return HTMLResponse(_WIZARD_HTML)


@app.post("/api/setup")
async def do_setup(request: Request) -> JSONResponse:
    data: dict[str, Any] = await request.json()
    errors: list[str] = []

    # Required fields
    if not data.get("robinhood_username"):
        errors.append("Robinhood email is required.")
    if not data.get("robinhood_password"):
        errors.append("Robinhood password is required.")
    if not data.get("anthropic_api_key"):
        errors.append("Anthropic API key is required.")
    if errors:
        return JSONResponse({"ok": False, "errors": errors})

    # Store secrets in keychain
    _store_secret("ROBINHOOD_PASSWORD", data["robinhood_password"])
    _store_secret("ANTHROPIC_API_KEY", data["anthropic_api_key"])
    if data.get("gemini_api_key"):
        _store_secret("GEMINI_API_KEY", data["gemini_api_key"])
    if data.get("robinhood_mfa_secret"):
        _store_secret("ROBINHOOD_MFA_SECRET", data["robinhood_mfa_secret"])
    if data.get("ntfy_url"):
        pass  # ntfy is not a secret, goes in .env

    # Build .env fields
    watchlist = data.get("watchlist", "AAPL,TSLA,NVDA,BTC,ETH").strip().upper()
    env_fields = {
        "ROBINHOOD_USERNAME": data["robinhood_username"].strip(),
        "AGENTIC_ACCOUNT_NUMBER": data.get("agentic_account", "").strip(),
        "DEFAULT_ACCOUNT_NUMBER": data.get("default_account", "").strip(),
        "PAPER_TRADE": "true" if data.get("paper_trade", True) else "false",
        "APPROVAL_THRESHOLD": data.get("approval_threshold", "medium"),
        "WATCHLIST": watchlist,
        "MAX_POSITION_PCT": str(round(float(data.get("max_position_pct", 0.10)), 2)),
        "STOP_LOSS_PCT": str(round(float(data.get("stop_loss_pct", 0.05)), 2)),
        "MAX_POSITIONS": str(int(data.get("max_positions", 5))),
        "DAILY_DRAWDOWN_LIMIT": str(round(float(data.get("daily_drawdown_limit", -0.05)), 2)),
        "MIN_CONFIDENCE": str(round(float(data.get("min_confidence", 0.65)), 2)),
        "MAX_POSITION_LOSS_USD": str(round(float(data.get("max_position_loss_usd", 75.0)), 2)),
        "MONTHLY_API_BUDGET": str(round(float(data.get("monthly_api_budget", 20.0)), 2)),
        "INTERVAL_OPEN": "90",
        "INTERVAL_PREMARKET": "180",
        "INTERVAL_AFTERHOURS": "180",
        "INTERVAL_CLOSED": "300",
        "WEB_HOST": "127.0.0.1",
        "WEB_PORT": "8000",
    }
    if data.get("ntfy_url"):
        env_fields["NTFY_URL"] = data["ntfy_url"].strip()

    _write_env(env_fields)

    # Shut down wizard after a short delay so the response reaches the browser
    def _stop():
        import time; time.sleep(1.5)
        _shutdown_event.set()
    threading.Thread(target=_stop, daemon=True).start()

    return JSONResponse({"ok": True})


@app.get("/api/prefill")
async def prefill() -> JSONResponse:
    """Return any existing .env values so the form can pre-populate on re-run."""
    if not _ENV_FILE.exists():
        return JSONResponse({})
    result: dict[str, str] = {}
    for line in _ENV_FILE.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            result[k.strip()] = v.strip()
    return JSONResponse(result)


# ── HTML ───────────────────────────────────────────────────────────────────────

_WIZARD_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Argus Setup</title>
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  :root {
    --bg: #0d1117; --surface: #161b22; --border: #30363d;
    --cyan: #00d4ff; --purple: #9b59b6; --green: #2ea44f;
    --text: #e6edf3; --muted: #8b949e; --red: #f85149;
  }
  body { background: var(--bg); color: var(--text); font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 2rem; }
  .card { background: var(--surface); border: 1px solid var(--border); border-radius: 12px; width: 100%; max-width: 600px; overflow: hidden; }
  .header { background: linear-gradient(135deg, #0d2137 0%, #1a0d2e 100%); padding: 2rem; text-align: center; border-bottom: 1px solid var(--border); }
  .header h1 { font-size: 2rem; font-weight: 700; letter-spacing: .15em; color: var(--cyan); }
  .header p { color: var(--muted); margin-top: .5rem; font-size: .9rem; }
  .steps { display: flex; border-bottom: 1px solid var(--border); }
  .step { flex: 1; padding: .75rem .5rem; text-align: center; font-size: .75rem; color: var(--muted); border-bottom: 2px solid transparent; cursor: default; transition: all .2s; }
  .step.active { color: var(--cyan); border-color: var(--cyan); }
  .step.done { color: var(--green); border-color: var(--green); }
  .body { padding: 2rem; }
  .section { display: none; }
  .section.active { display: block; }
  h2 { font-size: 1.1rem; margin-bottom: .4rem; }
  .hint { color: var(--muted); font-size: .82rem; margin-bottom: 1.5rem; line-height: 1.5; }
  .hint a { color: var(--cyan); }
  label { display: block; font-size: .85rem; color: var(--muted); margin-bottom: .3rem; margin-top: 1rem; }
  label span.req { color: var(--red); }
  input[type=text], input[type=email], input[type=password], input[type=url], input[type=number] {
    width: 100%; padding: .6rem .8rem; background: var(--bg); border: 1px solid var(--border);
    border-radius: 6px; color: var(--text); font-size: .9rem; outline: none; transition: border-color .2s;
  }
  input:focus { border-color: var(--cyan); }
  .row2 { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
  .toggle-row { display: flex; align-items: center; gap: .75rem; margin-top: 1rem; }
  .toggle { position: relative; width: 44px; height: 24px; flex-shrink: 0; }
  .toggle input { opacity: 0; width: 0; height: 0; }
  .slider { position: absolute; inset: 0; background: var(--border); border-radius: 24px; cursor: pointer; transition: .2s; }
  .slider:before { content: ''; position: absolute; width: 18px; height: 18px; left: 3px; bottom: 3px; background: white; border-radius: 50%; transition: .2s; }
  input:checked + .slider { background: var(--green); }
  input:checked + .slider:before { transform: translateX(20px); }
  .toggle-label { font-size: .85rem; }
  .range-row { display: flex; align-items: center; gap: 1rem; margin-top: .3rem; }
  input[type=range] { flex: 1; accent-color: var(--cyan); }
  .range-val { font-size: .85rem; color: var(--cyan); min-width: 3.5rem; text-align: right; font-family: monospace; }
  .watchlist-grid { display: flex; flex-wrap: wrap; gap: .5rem; margin-top: .75rem; }
  .chip { padding: .35rem .75rem; border-radius: 20px; border: 1px solid var(--border); font-size: .8rem; cursor: pointer; transition: all .15s; user-select: none; }
  .chip.on { background: var(--cyan); border-color: var(--cyan); color: #000; font-weight: 600; }
  .chip:not(.on):hover { border-color: var(--cyan); color: var(--cyan); }
  .custom-wl { margin-top: .75rem; }
  .footer { display: flex; justify-content: space-between; padding: 1.5rem 2rem; border-top: 1px solid var(--border); gap: 1rem; }
  button { padding: .65rem 1.5rem; border-radius: 6px; font-size: .9rem; font-weight: 600; cursor: pointer; border: none; transition: opacity .15s; }
  button:hover { opacity: .85; }
  .btn-back { background: var(--surface); color: var(--text); border: 1px solid var(--border); }
  .btn-next { background: var(--cyan); color: #000; margin-left: auto; }
  .btn-finish { background: var(--green); color: #fff; margin-left: auto; }
  .error-box { background: #2d1b1b; border: 1px solid var(--red); border-radius: 6px; padding: .75rem 1rem; margin-bottom: 1rem; font-size: .85rem; color: var(--red); display: none; }
  .done-screen { text-align: center; padding: 2rem 0; }
  .done-screen .icon { font-size: 3rem; }
  .done-screen h2 { margin: 1rem 0 .5rem; font-size: 1.3rem; }
  .cost-box { background: #1c1a0d; border: 1px solid #6e5e00; border-radius: 8px; padding: 1rem 1.2rem; margin-bottom: 1.5rem; }
  .cost-box .cost-title { font-size: .8rem; font-weight: 700; color: #e3c100; letter-spacing: .05em; margin-bottom: .6rem; }
  .cost-row { display: flex; justify-content: space-between; align-items: baseline; font-size: .82rem; margin: .3rem 0; }
  .cost-row .label { color: var(--muted); }
  .cost-row .amount { font-family: monospace; color: var(--text); }
  .cost-row .amount.high { color: #e3c100; }
  .cost-note { font-size: .75rem; color: var(--muted); margin-top: .6rem; line-height: 1.4; }
  .done-screen p { color: var(--muted); font-size: .9rem; line-height: 1.6; }
  .done-screen code { background: var(--bg); padding: .2rem .5rem; border-radius: 4px; font-family: monospace; color: var(--cyan); }
  kbd { background: var(--bg); border: 1px solid var(--border); border-radius: 4px; padding: .15rem .4rem; font-family: monospace; font-size: .82rem; }
</style>
</head>
<body>
<div class="card">
  <div class="header">
    <h1>ARGUS</h1>
    <p>AI trading agent — first-run setup</p>
  </div>

  <div class="steps">
    <div class="step active" id="s0">1 · Credentials</div>
    <div class="step" id="s1">2 · Accounts</div>
    <div class="step" id="s2">3 · Watchlist</div>
    <div class="step" id="s3">4 · Risk</div>
    <div class="step" id="s4">5 · Done</div>
  </div>

  <div class="body">
    <div class="error-box" id="errBox"></div>

    <!-- Step 0: Credentials -->
    <div class="section active" id="sec0">
      <h2>API keys &amp; Robinhood login</h2>
      <p class="hint">
        Secrets are stored in your <strong>OS keychain</strong> — never written to disk in plain text.
        Get your Anthropic key at <a href="https://console.anthropic.com" target="_blank">console.anthropic.com</a>.
        Gemini is optional but enables a second AI vote for higher-confidence trades.
      </p>

      <div class="cost-box">
        <div class="cost-title">💰 API COSTS — YOU WILL BE BILLED BY ANTHROPIC &amp; GOOGLE</div>
        <div class="cost-row"><span class="label">Claude (Anthropic) — per trading day</span><span class="amount high">~$0.50 – $2.00 / day</span></div>
        <div class="cost-row"><span class="label">Claude — per month (market days only)</span><span class="amount high">~$10 – $40 / month</span></div>
        <div class="cost-row"><span class="label">Gemini (Google) — per month</span><span class="amount">~$0.50 – $2 / month</span></div>
        <div class="cost-note">
          Cost scales with watchlist size and scan frequency. A 5-symbol watchlist scanning every 90s costs roughly <strong>$0.50/day</strong> in Claude tokens. A 20-symbol list at the same interval costs closer to <strong>$2/day</strong>.<br><br>
          Argus shows your live API spend in the dashboard. Set a monthly budget below — Argus will warn you when you're close.
        </div>
      </div>

      <label>Anthropic API key <span class="req">*</span> — <a href="https://console.anthropic.com" target="_blank" style="color:var(--cyan);font-size:.8rem">console.anthropic.com</a></label>
      <input type="text" id="ant_key" placeholder="sk-ant-..." autocomplete="off">

      <label>Google Gemini API key <small style="color:var(--muted)">(optional — enables Claude + Gemini ensemble) — <a href="https://aistudio.google.com" target="_blank" style="color:var(--cyan)">aistudio.google.com</a></small></label>
      <input type="text" id="gem_key" placeholder="AIza..." autocomplete="off">

      <label>Monthly API budget (USD) — Argus alerts you when spending approaches this</label>
      <div class="range-row">
        <input type="range" id="monthly_budget" min="5" max="100" value="20" step="5">
        <span class="range-val" id="monthly_budget_val">$20 / mo</span>
      </div>

      <label>Robinhood email <span class="req">*</span></label>
      <input type="email" id="rh_user" placeholder="you@example.com" autocomplete="off">

      <label>Robinhood password <span class="req">*</span></label>
      <input type="password" id="rh_pass" placeholder="••••••••" autocomplete="off">

      <label>Robinhood MFA secret <small style="color:var(--muted)">(optional — base32 string from authenticator setup)</small></label>
      <input type="text" id="rh_mfa" placeholder="JBSWY3DPEHPK3PXP..." autocomplete="off">
    </div>

    <!-- Step 1: Accounts -->
    <div class="section" id="sec1">
      <h2>Robinhood account numbers</h2>
      <p class="hint">
        Find these in Robinhood → <kbd>Account</kbd> → <kbd>Settings</kbd> → Account information.
        The format is a 9-digit number (e.g. <code>462038597</code>).<br><br>
        Argus manages two accounts: <strong>Agentic</strong> trades fully automatically.
        <strong>Default</strong> asks for your approval before each trade. Both run simultaneously.
        You can use the same account for both if you only have one.
      </p>

      <label>Agentic account number <span class="req">*</span> <small style="color:var(--muted)">(auto-trades)</small></label>
      <input type="text" id="acct_ag" placeholder="462038597" maxlength="12">

      <label>Default account number <small style="color:var(--muted)">(approval-gated — can be same as above)</small></label>
      <input type="text" id="acct_def" placeholder="462038597" maxlength="12">

      <div class="toggle-row" style="margin-top:1.5rem">
        <label class="toggle">
          <input type="checkbox" id="paper_mode" checked>
          <span class="slider"></span>
        </label>
        <span class="toggle-label"><strong>Paper trading mode</strong> — simulated orders, no real money. Recommended until you've run for a few weeks.</span>
      </div>

      <label style="margin-top:1.5rem">Push notifications via <a href="https://ntfy.sh" target="_blank" style="color:var(--cyan)">ntfy.sh</a> <small style="color:var(--muted)">(optional — paste your topic URL)</small></label>
      <input type="url" id="ntfy" placeholder="https://ntfy.sh/your-topic">
    </div>

    <!-- Step 2: Watchlist -->
    <div class="section" id="sec2">
      <h2>Your watchlist</h2>
      <p class="hint">
        Argus scans these symbols on every tick and runs its AI on each one.
        Pick the ones you want to trade — or type custom symbols below.
        The daily market screener will also discover movers &amp; earnings plays automatically.
      </p>

      <div class="watchlist-grid" id="chipGrid"></div>

      <div class="custom-wl">
        <label>Custom symbols <small style="color:var(--muted)">(comma-separated — add anything not in the list above)</small></label>
        <input type="text" id="custom_wl" placeholder="PLTR, LLY, ISRG">
      </div>
    </div>

    <!-- Step 3: Risk -->
    <div class="section" id="sec3">
      <h2>Risk guardrails</h2>
      <p class="hint">
        These limits protect your portfolio. Argus enforces them automatically — no trade can exceed these bounds no matter what the AI decides.
      </p>

      <label>Max position size — fraction of portfolio per trade</label>
      <div class="range-row">
        <input type="range" id="max_pos_pct" min="2" max="20" value="10" step="1">
        <span class="range-val" id="max_pos_pct_val">10%</span>
      </div>

      <label>Stop-loss — sell when a position drops this much from entry</label>
      <div class="range-row">
        <input type="range" id="stop_loss" min="1" max="15" value="5" step="1">
        <span class="range-val" id="stop_loss_val">5%</span>
      </div>

      <label>Max dollar loss per position — hard cap regardless of %</label>
      <div class="range-row">
        <input type="range" id="max_loss_usd" min="25" max="200" value="75" step="25">
        <span class="range-val" id="max_loss_usd_val">$75</span>
      </div>

      <div class="row2" style="margin-top:1rem">
        <div>
          <label>Max open positions</label>
          <input type="number" id="max_positions" value="5" min="1" max="20">
        </div>
        <div>
          <label>Min AI confidence to trade</label>
          <div class="range-row">
            <input type="range" id="min_conf" min="50" max="90" value="65" step="5">
            <span class="range-val" id="min_conf_val">65%</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Step 4: Done -->
    <div class="section" id="sec4">
      <div class="done-screen">
        <div class="icon">✅</div>
        <h2>Setup complete!</h2>
        <p>
          Your credentials are stored in the OS keychain and <code>.env</code> has been written.<br><br>
          Start Argus by running:<br><br>
          <code>argus</code><br><br>
          Then open <a href="http://127.0.0.1:8000" target="_blank" style="color:var(--cyan)">http://127.0.0.1:8000</a> in your browser.<br><br>
          This window will close in a few seconds.
        </p>
      </div>
    </div>
  </div>

  <div class="footer" id="footer">
    <button class="btn-back" id="btnBack" onclick="go(-1)" style="visibility:hidden">← Back</button>
    <button class="btn-next" id="btnNext" onclick="go(1)">Next →</button>
  </div>
</div>

<script>
const POPULAR = [
  'AAPL','NVDA','TSLA','MSFT','AMZN','GOOGL','META','AVGO','AMD',
  'PLTR','NFLX','SHOP','LLY','COIN','MU','UBER','DIS','HOOD',
  'BTC','ETH'
];
const DEFAULT_WL = new Set(['AAPL','TSLA','NVDA','BTC','ETH']);

let current = 0;
const NUM_STEPS = 4;
let selectedChips = new Set(DEFAULT_WL);

// Build chip grid
const grid = document.getElementById('chipGrid');
POPULAR.forEach(sym => {
  const chip = document.createElement('div');
  chip.className = 'chip' + (selectedChips.has(sym) ? ' on' : '');
  chip.textContent = sym;
  chip.onclick = () => {
    if (selectedChips.has(sym)) { selectedChips.delete(sym); chip.className = 'chip'; }
    else { selectedChips.add(sym); chip.className = 'chip on'; }
  };
  grid.appendChild(chip);
});

// Range labels
const ranges = [
  ['max_pos_pct',     v => v + '%'],
  ['stop_loss',       v => v + '%'],
  ['max_loss_usd',    v => '$' + v],
  ['min_conf',        v => v + '%'],
  ['monthly_budget',  v => '$' + v + ' / mo'],
];
ranges.forEach(([id, fmt]) => {
  const el = document.getElementById(id);
  const lbl = document.getElementById(id + '_val');
  el.oninput = () => { lbl.textContent = fmt(el.value); };
});

// Pre-fill from existing .env
fetch('/api/prefill').then(r => r.json()).then(d => {
  if (d.ROBINHOOD_USERNAME) document.getElementById('rh_user').value = d.ROBINHOOD_USERNAME;
  if (d.AGENTIC_ACCOUNT_NUMBER) document.getElementById('acct_ag').value = d.AGENTIC_ACCOUNT_NUMBER;
  if (d.DEFAULT_ACCOUNT_NUMBER) document.getElementById('acct_def').value = d.AGENTIC_ACCOUNT_NUMBER;
  if (d.NTFY_URL) document.getElementById('ntfy').value = d.NTFY_URL;
  if (d.PAPER_TRADE) document.getElementById('paper_mode').checked = d.PAPER_TRADE === 'true';
  if (d.WATCHLIST) {
    selectedChips = new Set(d.WATCHLIST.split(',').map(s => s.trim().toUpperCase()));
    document.querySelectorAll('.chip').forEach(c => {
      c.className = 'chip' + (selectedChips.has(c.textContent) ? ' on' : '');
    });
  }
  if (d.MAX_POSITION_PCT) { const v = Math.round(parseFloat(d.MAX_POSITION_PCT)*100); document.getElementById('max_pos_pct').value = v; document.getElementById('max_pos_pct_val').textContent = v + '%'; }
  if (d.STOP_LOSS_PCT) { const v = Math.round(parseFloat(d.STOP_LOSS_PCT)*100); document.getElementById('stop_loss').value = v; document.getElementById('stop_loss_val').textContent = v + '%'; }
  if (d.MAX_POSITION_LOSS_USD) { const v = parseInt(d.MAX_POSITION_LOSS_USD); document.getElementById('max_loss_usd').value = v; document.getElementById('max_loss_usd_val').textContent = '$' + v; }
  if (d.MIN_CONFIDENCE) { const v = Math.round(parseFloat(d.MIN_CONFIDENCE)*100); document.getElementById('min_conf').value = v; document.getElementById('min_conf_val').textContent = v + '%'; }
  if (d.MAX_POSITIONS) document.getElementById('max_positions').value = d.MAX_POSITIONS;
  if (d.MONTHLY_API_BUDGET) { const v = parseInt(parseFloat(d.MONTHLY_API_BUDGET)); document.getElementById('monthly_budget').value = v; document.getElementById('monthly_budget_val').textContent = '$' + v + ' / mo'; }
});

function showErr(msg) {
  const b = document.getElementById('errBox');
  b.textContent = msg; b.style.display = 'block';
  setTimeout(() => { b.style.display = 'none'; }, 4000);
}

function validate(step) {
  if (step === 0) {
    if (!document.getElementById('rh_user').value.trim()) { showErr('Robinhood email is required.'); return false; }
    if (!document.getElementById('rh_pass').value.trim()) { showErr('Robinhood password is required.'); return false; }
    if (!document.getElementById('ant_key').value.trim()) { showErr('Anthropic API key is required.'); return false; }
  }
  if (step === 1) {
    if (!document.getElementById('acct_ag').value.trim()) { showErr('Agentic account number is required.'); return false; }
  }
  return true;
}

function go(dir) {
  if (dir === 1 && !validate(current)) return;
  if (current + dir >= NUM_STEPS) { finish(); return; }
  current = Math.max(0, Math.min(NUM_STEPS - 1, current + dir));
  render();
}

function render() {
  document.querySelectorAll('.section').forEach((s, i) => s.className = 'section' + (i === current ? ' active' : ''));
  document.querySelectorAll('.step').forEach((s, i) => {
    s.className = 'step' + (i === current ? ' active' : '') + (i < current ? ' done' : '');
  });
  document.getElementById('btnBack').style.visibility = current > 0 ? 'visible' : 'hidden';
  const isLast = current === NUM_STEPS - 1;
  document.getElementById('btnNext').style.display = isLast ? 'none' : '';
  document.getElementById('btnNext').textContent = current === NUM_STEPS - 2 ? 'Finish →' : 'Next →';
  document.getElementById('footer').style.display = current === NUM_STEPS ? 'none' : '';
}

async function finish() {
  // Build watchlist: chips + custom
  const custom = document.getElementById('custom_wl').value.split(',').map(s => s.trim().toUpperCase()).filter(Boolean);
  const wl = [...new Set([...selectedChips, ...custom])].join(',');

  const payload = {
    robinhood_username: document.getElementById('rh_user').value.trim(),
    robinhood_password: document.getElementById('rh_pass').value.trim(),
    robinhood_mfa_secret: document.getElementById('rh_mfa').value.trim(),
    anthropic_api_key: document.getElementById('ant_key').value.trim(),
    gemini_api_key: document.getElementById('gem_key').value.trim(),
    agentic_account: document.getElementById('acct_ag').value.trim(),
    default_account: document.getElementById('acct_def').value.trim() || document.getElementById('acct_ag').value.trim(),
    paper_trade: document.getElementById('paper_mode').checked,
    ntfy_url: document.getElementById('ntfy').value.trim(),
    watchlist: wl,
    max_position_pct: parseInt(document.getElementById('max_pos_pct').value) / 100,
    stop_loss_pct: parseInt(document.getElementById('stop_loss').value) / 100,
    max_position_loss_usd: parseInt(document.getElementById('max_loss_usd').value),
    max_positions: parseInt(document.getElementById('max_positions').value),
    min_confidence: parseInt(document.getElementById('min_conf').value) / 100,
    monthly_api_budget: parseInt(document.getElementById('monthly_budget').value),
  };

  const btn = document.getElementById('btnNext');
  btn.textContent = 'Saving…'; btn.disabled = true;

  try {
    const res = await fetch('/api/setup', { method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(payload) });
    const data = await res.json();
    if (!data.ok) { showErr(data.errors?.join(' ') || 'Something went wrong.'); btn.textContent = 'Finish →'; btn.disabled = false; return; }
    current = NUM_STEPS - 1;
    render();
    document.getElementById('footer').style.display = 'none';
    setTimeout(() => window.close(), 5000);
  } catch(e) {
    showErr('Network error — is the wizard still running?');
    btn.textContent = 'Finish →'; btn.disabled = false;
  }
}
</script>
</body>
</html>
"""


# ── entry point ────────────────────────────────────────────────────────────────

def main() -> None:
    port = 8888
    print(f"\n  Argus Setup Wizard → http://localhost:{port}\n")

    def _open_browser():
        import time; time.sleep(1.2)
        webbrowser.open(f"http://localhost:{port}")
    threading.Thread(target=_open_browser, daemon=True).start()

    config = uvicorn.Config(app, host="127.0.0.1", port=port, log_level="warning")
    server = uvicorn.Server(config)

    def _watch_shutdown():
        _shutdown_event.wait()
        print("\n  Setup complete. Run:  argus\n")
        server.should_exit = True
    threading.Thread(target=_watch_shutdown, daemon=True).start()

    server.run()


if __name__ == "__main__":
    main()
